### ISSUE TITLE
fatal error on wordpress 4.1.1

### ISSUE THREAD

**Issue by dajeux** [paulperkins/bimbler-rsvp#1]
Hi, first of all, thanks for sharing.
when i try to activate rsvp plugin : 
fatal error : /wordpress411/wp-content/plugins/bimbler-rsvp/widgets/bimbler-widgets.php): failed to open stream: No such file or directory in /wordpress411/wp-content/plugins/bimbler-rsvp-master/class-bimbler-rsvp.php on line 349 Fatal error: require_once(): Failed opening required '/wordpress411/wp-content/plugins/bimbler-rsvp/widgets/bimbler-widgets.php' (include_path='.:/lib:/libs:/libraries:/src:/vendor:/vendors:/var/lib/openshift/54c79978e0b8cd724600002f/php/phplib/pear/pear/php:/usr/share/pear') in /wordpress411/wp-content/plugins/bimbler-rsvp-master/class-bimbler-rsvp.php on line 349

the plugin reminder activates successfully.
thanks

**Comment by dajeux** [comment]
hi,
I renamed the folder inside zip without "master", then it activates well.
thank you

**Comment by paulperkins** [comment]
Excellent - thanks for the feedback!

I'll make sure I add this to the readme file.
